In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import re

In [2]:
df=pd.read_csv("C:\\Users\\Acer\\Downloads\\smartphones - smartphones.csv")

In [3]:
df.head()

model    price  rating  \
0              OnePlus 11 5G  ₹54,999    89.0   
1  OnePlus Nord CE 2 Lite 5G  ₹19,989    81.0   
2      Samsung Galaxy A14 5G  ₹16,499    75.0   
3       Motorola Moto G62 5G  ₹14,999    81.0   
4         Realme 10 Pro Plus  ₹24,999    82.0   

                                       sim  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                         processor                        ram  \
0  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor  12 GB RAM, 256 GB inbuilt   
1     Snapdragon 695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
2        Exynos 1330, Octa Core, 2.4 GHz Processor    4 GB RAM, 64 GB inbuilt   
3    Snapdragon  695, Octa Core, 2.2 GHz Processor   6 GB RAM, 128 GB inbuilt   
4     Dimensity 1080, Octa Core, 2.6 GHz Processor   6 GB RAM, 128 GB inbuilt   

                                    battery  \
0  5000 mAh Battery with 100W Fast Charging   
1   5000 mAh Battery with 33W Fast Charging   
2   5000 mAh Battery with 15W Fast Charging   
3       5000 mAh Battery with Fast Charging   
4   5000 mAh Battery with 67W Fast Charging   

                                             display  \
0  6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1  6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2  6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3  6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4  6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   

                                              camera  \
0  50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1  64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2  50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3  50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4  108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   

                               card           os  
0         Memory Card Not Supported  Android v13  
1   Memory Card (Hybrid), upto 1 TB  Android v12  
2  Memory Card Supported, upto 1 TB  Android v13  
3   Memory Card (Hybrid), upto 1 TB  Android v12  
4         Memory Card Not Supported  Android v13

In [4]:
df['brand']=df['model'].apply(lambda x: x.split()[0])
df['brand'].unique()

array(['OnePlus', 'Samsung', 'Motorola', 'Realme', 'Apple', 'Xiaomi',
       'Nothing', 'Oppo', 'Vivo', 'OPPO', 'Poco', 'iQOO', 'Jio', 'Gionee',
       'Tecno', 'Tesla', 'Google', 'Infinix', 'Nokia', 'Cola', 'Letv',
       'POCO', 'iKall', 'LeEco', 'Duoqin', 'Lava', 'Honor', 'Nubia',
       'Redmi', 'Asus', 'itel', 'Royole', 'Sony', 'Oukitel', 'Vertu',
       'BLU', 'Lyf', 'Itel', 'Huawei', 'ZTE', 'Lenovo', 'LG', 'Namotel',
       'Eunity', 'Micromax', 'Zanco', 'Karbonn', 'Leitz', 'CAT', 'DIZO',
       'BlackZone', 'Doogee', 'TCL', 'Sharp', 'Blackview', 'XTouch'],
      dtype=object)

In [5]:
def price_extract(text):
    partten="₹\d+,\d+,\d+|₹\d+,\d+|₹\d+"
    match=re.search(partten,text)
    t=match[0]
    return int(t[1:].replace(',',''))

In [6]:
df['price_clean']=df['price'].apply(price_extract)
df['price_clean'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1020 entries, 0 to 1019
Series name: price_clean
Non-Null Count  Dtype
--------------  -----
1020 non-null   int64
dtypes: int64(1)
memory usage: 8.1 KB


In [7]:
df['no_of_sim']=df['sim'].apply(lambda x: 2 if 'Dual Sim' in x else 1)
df['5g']=df['sim'].apply(lambda x: 1 if '5G' in x else 0)
df['nfc']=df['sim'].apply(lambda x: 1 if 'NFC' in x else 0)
df['irb']=df['sim'].apply(lambda x: 1 if 'IR Blaster' in x else 0)
df['irb'].unique()

array([0, 1], dtype=int64)

In [8]:
def core_extract(text):
    partten='\w+\sCore'
    match=re.search(partten,text)
    map_dir={'Octa Core':8,
              'Hexa Core':6,
              'Quad Core':4,
              'Dual Core':2,
              'Single Core':1
            }
    if match:
        return map_dir[match[0]]
    else:
        return None

In [9]:
# df['core'].unique()

In [10]:
def extract_clock_speed(text):
    partten="\d+.\d+\sGHz|\d+\sGHz"
    match=re.search(partten,text)
    if match:
        return float(match[0][:-4])
    else:
        return np.nan

In [11]:
df['processor_name']=df['processor'].apply(lambda x: x.split(',')[0].strip())
df['core']=df['processor'].apply(core_extract)
df['clock_speed']=df['processor'].apply(extract_clock_speed)
df['clock_speed'].unique()

array([3.2 , 2.2 , 2.4 , 2.6 , 3.22, 2.5 , 3.  , 2.3 , 2.85, 2.  , 2.84,
        nan, 2.65, 2.9 , 2.36, 1.8 , 3.1 , 2.05, 3.05, 1.4 , 1.3 , 1.82,
       1.6 , 1.1 , 2.8 , 2.73, 2.7 , 1.  , 1.5 , 2.96, 2.35, 2.37, 3.13,
       1.99, 2.86, 1.95, 2.1 , 1.2 ])

In [12]:
def extract_ram(text):
    partten="(\d+)\sGB\sRAM"
    match=re.search(partten,text)
    if match:
        return int(match.group(1))
    else:
        return np.nan

In [13]:
def extract_rom(text):
    partten="(\d+)\sGB\sinbuilt"
    match=re.search(partten,text)
    if match:
        return int(match.group(1))
    else:
        return np.nan

In [14]:
# extract RAM and ROM sizes using regular expressions
df['ram_size']=df['ram'].apply(extract_ram)
df['rom_size']=df['ram'].apply(extract_rom)
df['rom_size'].unique()
# df['rom_size'] = df['ram'].apply(lambda x: int(re.search(r'(\d+)\s*GB\s*inbuilt', x).group(1)))

array([256., 128.,  64.,  32., 512.,  nan,   4.,  16.,   8.])

In [15]:
def extract_mah(text):
    partten='(\d+)\smAh'
    match=re.search(partten,text)
    if match:
        return int(match.group(1))
    else:
        return 1000

In [16]:
def extract_charging_speed(text):
    partten='(\d+)W'
    match=re.search(partten,text)
    if match:
        return int(match.group(1))
    else:
        return 10

In [17]:
df['mah']=df['battery'].apply(extract_mah)
df['charging_speed']=df['battery'].apply(extract_charging_speed)
df['charging_speed'].unique()

array([100,  33,  15,  10,  67,  25, 120,  80,  18,  45,  66,  44, 210,
        30, 150,  68,  50,  20,  65, 180, 125,  40,  60, 200, 240,  19,
        21, 135, 165,   5,  27,  55,   2], dtype=int64)

In [18]:
def extract_screen_size(text):
    partten='(\d+.\d+|\d+)\sinches'
    match=re.search(partten,text)
    if match:
        return float(match.group(1))
    else:
        return np.nan

In [19]:
def extract_refresh_rate(text):
    partten='(\d+)\sHz'
    match=re.search(partten,text)
    if match:
        return int(match.group(1))
    else:
        return 60

In [20]:
def extract_screen_resoultion(text):
    partten='(\d+)\sx\s\d+\spx'
    match=re.search(partten,text)
    if match:
        temp=int(match.group(1))
        if temp>=2200:
            return 2200
        elif temp>=1440:
            return 1440
        elif temp>=1080:
            return 1080
        elif temp>=720:
            return 720
        else:
            temp
    else:
        return 100

In [21]:
# df_new.head()

In [22]:
df['screen_size']=df['display'].apply(extract_screen_size)
df['screen_refrash_rate']=df['display'].apply(extract_refresh_rate)
df['screen_resoultion']=df['display'].apply(extract_screen_resoultion)
df['screen_resoultion'].unique()

array([1440., 1080.,  720.,  100., 2200.,   nan])

In [23]:
def extract_rear_cam(text):
    partten=r"(\d+)[A-Za-z0-9\s\+]+Front"
    match=re.search(partten,str(text))
    if match:
        return int(match.group(1))
    else:
        return None

In [24]:
def extract_rear_cam(text):
    partten="&\s(\d+)\sMP\sFront"
    match=re.search(partten,str(text))
    if match:
        return int(match.group(1))
    else:
        return None

In [25]:
df['rear_cam']=df['camera'].apply(extract_rear_cam)
df['front_cam']=df['camera'].apply(extract_rear_cam)
df['front_cam'].unique()

array([16., 13.,  8., 12., 32.,  5., 50., 40., nan, 10., 60.,  2.,  7.,
       44., 20., 24., 25.])

In [26]:
# df['card'].unique()

In [27]:
# text='Memory Card Not Supported'
# ('Not' not in text)

In [28]:
df['memory_card']=df['card'].apply(lambda x: 1 if 'Not' not in str(x) else 0)
df['hybrid_card']=df['card'].apply(lambda x: 1 if 'Hybrid' in str(x) else 0)
df['hybrid_card'].unique()

array([0, 1], dtype=int64)

In [29]:
def map_os(os):
    if pd.isna(os):
        return 'other'
    elif 'android' in os.lower():
        return 'android'
    elif 'ios' in os.lower():
        return 'ios'
    else:
        return 'other'

In [30]:
def extract_os_version(text):
    if pd.isna(text):
        return None
    partten="v(\d+.d+|\d+)"
    match=re.search(partten,text)
    if match:
        return int(match.group(1))
    else:
        return None

In [31]:
df['os_type']=df['os'].apply(map_os)
df['os_version']=df['os'].apply(extract_os_version)
df['os_version'].unique()

array([13., 12., 16., nan, 15., 11., 10.,  2.,  8.,  9., 17.,  4.,  5.,
        3.,  6.,  7.])

In [32]:
df_new=df.drop(['model', 'price','sim', 'processor', 'ram', 'battery',
       'display', 'camera', 'card', 'os','os_version'],axis=1)
df_new

rating     brand  price_clean  no_of_sim  5g  nfc  irb  \
0       89.0   OnePlus        54999          2   1    1    0   
1       81.0   OnePlus        19989          2   1    0    0   
2       75.0   Samsung        16499          2   1    0    0   
3       81.0  Motorola        14999          2   1    0    0   
4       82.0    Realme        24999          2   1    0    0   
...      ...       ...          ...        ...  ..  ...  ...   
1015    83.0  Motorola        34990          2   1    0    0   
1016    75.0     Honor        14990          2   1    0    0   
1017    85.0      POCO        28990          2   1    1    1   
1018    80.0  Motorola        19990          2   1    1    0   
1019    74.0   Samsung        24990          2   1    0    0   

           processor_name  core  clock_speed  ...   mah  charging_speed  \
0       Snapdragon 8 Gen2   8.0         3.20  ...  5000             100   
1          Snapdragon 695   8.0         2.20  ...  5000              33   
2             Exynos 1330   8.0         2.40  ...  5000              15   
3         Snapdragon  695   8.0         2.20  ...  5000              10   
4          Dimensity 1080   8.0         2.60  ...  5000              67   
...                   ...   ...          ...  ...   ...             ...   
1015    Snapdragon 8 Gen1   8.0         3.00  ...  5000               2   
1016     Snapdragon  480+   8.0         2.20  ...  5000               5   
1017       Dimensity 8100   8.0         2.85  ...  5080              67   
1018       Snapdragon 695   8.0         2.20  ...  5000              10   
1019  Octa Core Processor   8.0          NaN  ...  5000              10   

      screen_size  screen_refrash_rate  screen_resoultion  rear_cam  \
0            6.70                  120             1440.0      16.0   
1            6.59                  120             1080.0      16.0   
2            6.60                   90             1080.0      13.0   
3            6.55                  120             1080.0      16.0   
4            6.70                  120             1080.0      16.0   
...           ...                  ...                ...       ...   
1015         6.67                  120             1080.0      16.0   
1016         6.50                   60              720.0       8.0   
1017         6.60                  144             1080.0      16.0   
1018         6.80                   60             1080.0      32.0   
1019         6.50                   60             1080.0      32.0   

      front_cam  memory_card  hybrid_card  os_type  
0          16.0            0            0  android  
1          16.0            1            1  android  
2          13.0            1            0  android  
3          16.0            1            1  android  
4          16.0            0            0  android  
...         ...          ...          ...      ...  
1015       16.0            1            0    other  
1016        8.0            1            0  android  
1017       16.0            0            0  android  
1018       32.0            1            0  android  
1019       32.0            1            0  android  

[1020 rows x 22 columns]

In [33]:
df_new.isna().sum()

rating                 141
brand                    0
price_clean              0
no_of_sim                0
5g                       0
nfc                      0
irb                      0
processor_name           0
core                    40
clock_speed             75
ram_size                41
rom_size                41
mah                      0
charging_speed           0
screen_size             33
screen_refrash_rate      0
screen_resoultion       21
rear_cam               110
front_cam              110
memory_card              0
hybrid_card              0
os_type                  0
dtype: int64

In [34]:
# df_new.isna().sum()[df_new.isna().sum()>0]

In [35]:
# df[df_new['front_cam'].isna()].iloc[:,:11]

In [36]:
# df_new['rating'].values.reshape(-1,1)

In [37]:
# from sklearn.impute import KNNImputer
# impt=KNNImputer(n_neighbors=5)
# df_new['rating_impted']=impt.fit_transform(df_new['rating'].values.reshape(-1,1))

In [38]:
# df_new['rating_impted'].unique()

In [39]:
df_new['rating'].describe()

count    879.000000
mean      78.258248
std        7.402854
min       60.000000
25%       74.000000
50%       80.000000
75%       84.000000
max       89.000000
Name: rating, dtype: float64

In [40]:
df_new['rating'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1020 entries, 0 to 1019
Series name: rating
Non-Null Count  Dtype  
--------------  -----  
879 non-null    float64
dtypes: float64(1)
memory usage: 8.1 KB


In [41]:
df_new['rating']=df_new['rating'].fillna(round(df_new['rating'].mean(),2))

In [42]:
df_new.isna().sum()[df_new.isna().sum()>0]

core                  40
clock_speed           75
ram_size              41
rom_size              41
screen_size           33
screen_resoultion     21
rear_cam             110
front_cam            110
dtype: int64

In [43]:
# df_new=df_new.drop('rating_impted',axis=1)

In [44]:
df_new=df_new.dropna()

In [45]:
df_new.iloc[:5,13:]

charging_speed  screen_size  screen_refrash_rate  screen_resoultion  \
0             100         6.70                  120             1440.0   
1              33         6.59                  120             1080.0   
2              15         6.60                   90             1080.0   
3              10         6.55                  120             1080.0   
4              67         6.70                  120             1080.0   

   rear_cam  front_cam  memory_card  hybrid_card  os_type  
0      16.0       16.0            0            0  android  
1      16.0       16.0            1            1  android  
2      13.0       13.0            1            0  android  
3      16.0       16.0            1            1  android  
4      16.0       16.0            0            0  android

In [47]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 864 entries, 0 to 1018
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   rating               864 non-null    float64
 1   brand                864 non-null    object 
 2   price_clean          864 non-null    int64  
 3   no_of_sim            864 non-null    int64  
 4   5g                   864 non-null    int64  
 5   nfc                  864 non-null    int64  
 6   irb                  864 non-null    int64  
 7   processor_name       864 non-null    object 
 8   core                 864 non-null    float64
 9   clock_speed          864 non-null    float64
 10  ram_size             864 non-null    float64
 11  rom_size             864 non-null    float64
 12  mah                  864 non-null    int64  
 13  charging_speed       864 non-null    int64  
 14  screen_size          864 non-null    float64
 15  screen_refrash_rate  864 non-null    in

In [46]:
# df_new.to_csv("F:\\1_Study_Materials\\kaggel\\Fyenn Labs\\cell_phone.csv",index=False)